---
- name: Create Docker registry docroot.
  file:
    state: directory
    path: "{{ docker_registry_data_directory }}"
    mode: "0755"

- name: Run docker registry container
  docker_container:
    exposed_ports: 
      - 5000
    image: "registry:2"
    name: registry
    published_ports: 
      - "{{ docker_registry_expose_port }}:5000"
    volumes:
      - "{{ docker_registry_data_directory }}:{{ docker_registry_data_directory }}"
    pull: no
    restart_policy: unless-stopped
    # "reloaded" does not appear to be idempotent
    state: started
    env:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "{{ docker_registry_data_directory }}"
